# Generated by Django 5.0.2 on 2024-04-19 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('RC', 'RC'), ('CE', 'CE'), ('PEP', 'PEP'), ('DNI', 'DNI'), ('SCR', 'SCR'), ('PA', 'PA')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Unión libre', 'Unión libre'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Intersexual', 'Intersexual'), ('Otro', 'Otro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijos', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 o más', '5 o más')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(choices=[('Desempleado(a)', 'Desempleado(a)'), ('Empleado(a)', 'Empleado(a)'), ('Independiente', 'Independiente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sangre', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Basica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.IntegerField(null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion_residencia', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_app.documento')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal_app.estado')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal_app.genero')),
                ('hijos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal_app.hijos')),
                ('ocupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal_app.ocupacion')),
                ('sangre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal_app.sangre')),
            ],
        ),
        migrations.CreateModel(
            name='Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_medico', models.TextField(max_length=250)),
                ('sistematologia_actual', models.TextField(max_length=250)),
                ('medicamentos_actuales', models.TextField(max_length=250)),
                ('examenes_laboratorio', models.TextField(max_length=250)),
                ('examenes_imagenologia', models.TextField(max_length=250)),
                ('antecedentes_familiares', models.TextField(max_length=250)),
                ('antecedentes_personales', models.TextField(max_length=250)),
                ('tension_arterial', models.FloatField()),
                ('glucemia', models.FloatField()),
                ('sat_O2', models.IntegerField()),
                ('basica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_app.basica')),
            ],
        ),
    ]
